### PR TITLE
New stickers: 'humane generated content' and 'plug and pray'

### PR DESCRIPTION
**Pull request by schorschii**
You may like my stickers too

### CODE REVIEW

**Comment by TheJJ** [comment]
hey! thanks for the submission.
what licenses are those stickers?

- shouldn't it be "human" generated content? humane ("menschenwürdig") doesn't seem right
- what for is plug and pray? how does the icon relate to that? :)

we do have a quite high entry barrier for quality submissions and i think these stickers need some quality/humor enhancements :stuck_out_tongue:

**Comment by schorschii** [comment]
Yes, I removed the 'e'.
The plug and pray icon shows folded hands --> pray.
Both icons are from the Google [material icons](https://fonts.google.com/icons?icon.query=pray), so I added the [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).

**Comment by schorschii** [comment]
Closed due to lack of humor, I guess.

**Review by TheJJ — APPROVED** [review]
thx, sorry for being busy :)

**Comment by schorschii** [comment]
Thanks :)

**Pull request merged**
